[package]
edition.workspace      = true
license-file.workspace = true
name                   = "ibc-union-light-client"
repository.workspace   = true
version                = "0.1.0"

[dependencies]
cosmwasm-schema       = { workspace = true, package = "cosmwasm-schema" }
cosmwasm-std          = { workspace = true, package = "cosmwasm-std" }
cw-storage-plus       = { workspace = true, package = "cw-storage-plus" }
ibc-union-msg         = { workspace = true }
macros.workspace      = true
schemars              = { workspace = true }
serde                 = { workspace = true }
serde-utils.workspace = true
thiserror.workspace   = true
unionlabs.workspace   = true

[lints]
workspace = true
