[package]
authors.workspace      = true
edition.workspace      = true
license-file.workspace = true
name                   = "native-token-minter"
publish.workspace      = true
repository.workspace   = true
version                = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema             = { workspace = true }
cosmwasm-std                = { workspace = true }
cw-storage-plus             = { workspace = true }
thiserror                   = { workspace = true }
token-factory-api           = { workspace = true }
ucs03-zkgm-token-minter-api = { workspace = true }

[lints]
workspace = true
