[package]
authors      = ["Union Labs"]
edition      = "2021"
license-file = { workspace = true }
name         = "evm-in-cosmos-light-client"
publish      = false
version      = "0.1.0"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cometbls-light-client             = { workspace = true, features = ["library"] }
cosmwasm-std                      = { workspace = true, features = ["abort"] }
ethereum-light-client-types       = { workspace = true, features = ["serde", "ethabi", "bincode"] }
state-lens-ics23-mpt-light-client-types = { workspace = true, features = ["serde", "ethabi", "bincode"] }
evm-storage-verifier              = { workspace = true }
ibc-union-light-client            = { workspace = true }
ibc-union-msg                     = { workspace = true }
ibc-union-spec                    = { workspace = true }
ics23                             = { workspace = true }
rlp                               = { workspace = true }
serde                             = { workspace = true, features = ["derive"] }
thiserror                         = { workspace = true }
unionlabs                         = { workspace = true, features = ["ethabi", "stargate", "bincode"] }

[features]
default = []
# enabling this feature disables exposing the entrypoints and setting `#[global_allocator]`
library = []
