[package]
authors = []
name    = "ibc"
version = "1.0.0"

[addresses]
ibc       = "_"
ping_pong = "_"
ucs01 = "_"
zero_account = "0000000000000000000000000000000000000000000000000000000000000000"

[dev-addresses]
ibc       = "0x22222"
ping_pong = "0x1111"
ucs01 = "0x4444444444444"

[dependencies.AptosFramework]
git    = "https://github.com/aeryz/aptos-core.git"
rev    = "d34bb3e3dad03241967c0263a6f1fcfe6bccb7d7"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
