[package]
authors = []
name    = "ibc"
version = "1.0.0"

[addresses]
ibc = "0x4462dcd2422972dc3002a60403c15450982e88bc9c7999863ea8e2117f0b4d23"

[dev-addresses]
ibc = "0x22222"

[dependencies.AptosFramework]
git    = "https://github.com/aeryz/aptos-core.git"
rev    = "d34bb3e3dad03241967c0263a6f1fcfe6bccb7d7"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
