[package]
authors        = []
name           = "ucs03-zkgm"
upgrade_policy = "compatible"
version        = "1.0.0"

[addresses]
ibc  = "0x4462dcd2422972dc3002a60403c15450982e88bc9c7999863ea8e2117f0b4d23"
zkgm = "0xcebf41f47bdde649131694af50980b70ecd328d88a9b6c2993dae6405b0c88ed"

[dev-addresses]
ibc  = "0x22222"
zkgm = "0xbeef"

[dependencies.AptosFramework]
git    = "https://github.com/aeryz/aptos-core.git"
rev    = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
ibc = { local = "../move-ibc" }

[dev-dependencies]
