[package]
authors      = ["Hussein Ait Lahcen <hussein.aitlahcen@gmail.com>"]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "union-ibc-msg"
repository   = "https://github.com/unionlabs/union"
version      = "1.0.0"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ibc-solidity = { workspace = true, features = ["serde"] }
serde        = { workspace = true, features = ["derive"] }
unionlabs    = { workspace = true, features = ["ethabi"] }
