[package]
authors      = ["Hussein Ait Lahcen <hussein.aitlahcen@gmail.com>"]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "ibc-union"
repository   = "https://github.com/unionlabs/union"
version      = "1.0.0"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
alloy           = { workspace = true, features = ["sol-types"] }
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true, features = ["abort"] }
cw-storage-plus = { workspace = true }
ethabi          = { workspace = true }
hex             = { workspace = true }
ibc-solidity    = { workspace = true, features = ["serde"] }
ibc-union-msg   = { workspace = true }
ibc-union-spec  = { workspace = true, features = ["ethabi"] }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
strum           = { version = "0.26.3", features = ["derive"] }
thiserror       = { workspace = true }
unionlabs       = { workspace = true, features = ["ethabi"] }
