[package]
authors = ["Union Labs"]
edition = "2021"
license = "BSL-1.1"
name    = "cometbls-light-client"
publish = false
version = "0.1.0"

[lints]
workspace = true

[package.metadata.crane]
test-include = ["cosmwasm/union-ibc/light-clients/cometbls/src/test"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytes                     = { workspace = true }
cometbls-groth16-verifier = { workspace = true }
cosmwasm-std                = { version = "2.1.4", features = ["abort", "iterator", "cosmwasm_2_1"] }
hex                       = { workspace = true }
schemars                  = { workspace = true }
serde                     = { workspace = true, features = ["derive"] }
thiserror                 = { workspace = true }
union-ibc-light-client      = { workspace = true }
union-ibc-msg               = { workspace = true }
cometbls-light-client-types = { workspace = true, features = ["serde", "ethabi"] }
ics23                       = { workspace = true }
unionlabs                   = { workspace = true, features = ["ethabi"] }

[dev-dependencies]
base64      = { workspace = true }
lazy_static = "1.4.0"
serde_json  = { workspace = true }


[features]
