[alias]
integration-test = "test --test integration"
schema           = "run --bin schema"
unit-test        = "test --lib"
wasm             = "build --release --lib --target wasm32-unknown-unknown"
wasm-debug       = "build --lib --target wasm32-unknown-unknown"
